language: python
python:
    - "3.5"
cache:
  pip: true
  yarn: true
  directories:
    - node_modules

env:
  - TOXENV=django20

before_install:
  - nvm install
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn
  - yarn build
  - yarn build --env.project=leadbook
  - pip install tox

script: tox

notifications:
  slack: techproitservices:XsEF41X8AaQfMPg9I5XL10Gr
